services:
  evd_events_db:
    image: postgres:17.2-alpine
    container_name: evd_events_postgres-17.2
    volumes:
      - evd_events_postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
  evd_events_web:
    build: .
    command: "./bin/rails server -b 0.0.0.0"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - FEDERATED_APP_BASE_URL=${FEDERATED_APP_BASE_URL}
    volumes:
      - .:/rails
      - evd_events_app_storage:/rails/storage
    depends_on:
      - evd_events_db
    ports:
      - "3001:3000"

volumes:
  evd_events_postgres_data: {}
  evd_events_app_storage: {}
