development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cesarvalderrama
  database: events_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cesarvalderrama
  database: events_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cesarvalderrama
  database: events_production
